modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

# Эта строчка заставляет Forge автоматически включать наш миксин камеры дрона!
mixinConfigs=["fly_drone.mixins.json"]

[[mods]]
modId="fly_drone"
version="1.0.0"
displayName="Fly Drone"
authors="Zzynes"
description='''
Реалистичный мод на FPV-дроны с физикой полета а-ля Do a Barrel Roll, кастомными кумулятивными взрывами, прогрузкой чанков и управлением с пульта!
'''

[[dependencies.fly_drone]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fly_drone]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
