modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="elemental_awakening"
version="1.0.0"
displayName="Elemental Awakening"
logoFile="icon.png"
authors="Wizard"
description='''
Глобальный магический мод на стихии: Земля, Огонь, Вода, Ветер! С рангами и древом прокачки.
'''

[[dependencies.elemental_awakening]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.elemental_awakening]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
