modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="immersive_matrix"
version="1.0.0"
displayName="Immersive Matrix"
authors="Zzynex"
description="''"

[[dependencies.immersive_matrix]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.immersive_matrix]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1, 1.21)"
ordering="NONE"
side="BOTH"
